package com.yxb.cms.dao.input;

import java.util.List;
import java.util.Map;

import com.data.util.MyBatisRepository;
import com.yxb.cms.model.input.TbSubUtmSource;

@MyBatisRepository
public interface TbSubUtmSourceMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sub_utm_source
     * @mbggenerated  Mon Aug 24 18:02:13 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sub_utm_source
     * @mbggenerated  Mon Aug 24 18:02:13 CST 2015
     */
    int insert(TbSubUtmSource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sub_utm_source
     * @mbggenerated  Mon Aug 24 18:02:13 CST 2015
     */
    TbSubUtmSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sub_utm_source
     * @mbggenerated  Mon Aug 24 18:02:13 CST 2015
     */
    List<TbSubUtmSource> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sub_utm_source
     * @mbggenerated  Mon Aug 24 18:02:13 CST 2015
     */
    int updateByPrimaryKey(TbSubUtmSource record);

    int selectCount(Map<String, Object> paramMap);
    
    List<TbSubUtmSource> select(Map<String, Object> paramMap);
    
    List<TbSubUtmSource> selectExcel(Map<String, Object> paramMap);
}