package com.yxb.cms.model.input;

import java.util.Date;

public class TbDailyInput {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_daily_input.date_
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    private String date;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_daily_input.utm_source_id
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    private Integer utmSourceId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_daily_input.consume
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    private Double consume;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_daily_input.discount
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    private Float discount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_daily_input.display
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    private Integer display;
    
    private Integer exposure;
    
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_daily_input.click
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    private Integer click;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_daily_input.comment
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    private String comment;
    
    
    private Integer downloads;
    
    

    
    public Integer getExposure() {
		return exposure;
	}

	public void setExposure(Integer exposure) {
		this.exposure = exposure;
	}

	public Integer getDownloads() {
		return downloads;
	}

	public void setDownloads(Integer downloads) {
		this.downloads = downloads;
	}



    public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	/**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_daily_input.utm_source_id
     * @return  the value of tb_daily_input.utm_source_id
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public Integer getUtmSourceId() {
        return utmSourceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_daily_input.utm_source_id
     * @param utmSourceId  the value for tb_daily_input.utm_source_id
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public void setUtmSourceId(Integer utmSourceId) {
        this.utmSourceId = utmSourceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_daily_input.consume
     * @return  the value of tb_daily_input.consume
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public Double getConsume() {
        return consume;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_daily_input.consume
     * @param consume  the value for tb_daily_input.consume
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public void setConsume(Double consume) {
        this.consume = consume;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_daily_input.discount
     * @return  the value of tb_daily_input.discount
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_daily_input.discount
     * @param discount  the value for tb_daily_input.discount
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_daily_input.display
     * @return  the value of tb_daily_input.display
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public Integer getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_daily_input.display
     * @param display  the value for tb_daily_input.display
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public void setDisplay(Integer display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_daily_input.click
     * @return  the value of tb_daily_input.click
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public Integer getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_daily_input.click
     * @param click  the value for tb_daily_input.click
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public void setClick(Integer click) {
        this.click = click;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_daily_input.comment
     * @return  the value of tb_daily_input.comment
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_daily_input.comment
     * @param comment  the value for tb_daily_input.comment
     * @mbggenerated  Tue Jun 30 10:13:43 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}