package com.yxb.cms.model.input;

public class TbUtmSource {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_utm_source.id
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    private Integer id;
    
    private String key;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_utm_source.description
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_utm_source.category
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    private String category;
    
    private String parentCategory;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_utm_source.platform
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    private String platform;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_utm_source.charge_type
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    private String chargeType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_utm_source.abbreviation
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    private String abbreviation;

    private String landingPage;
    
    private String downloadPage;
    
    private String principal;
    
    private String superior;
    
    
    
	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getPrincipal() {
		return principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public String getSuperior() {
		return superior;
	}

	public void setSuperior(String superior) {
		this.superior = superior;
	}

	public String getParentCategory() {
		return parentCategory;
	}

	public void setParentCategory(String parentCategory) {
		this.parentCategory = parentCategory;
	}

	public String getLandingPage() {
		return landingPage;
	}

	public void setLandingPage(String landingPage) {
		this.landingPage = landingPage;
	}

	public String getDownloadPage() {
		return downloadPage;
	}

	public void setDownloadPage(String downloadPage) {
		this.downloadPage = downloadPage;
	}

	/**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_utm_source.id
     * @return  the value of tb_utm_source.id
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_utm_source.id
     * @param id  the value for tb_utm_source.id
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_utm_source.description
     * @return  the value of tb_utm_source.description
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_utm_source.description
     * @param description  the value for tb_utm_source.description
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_utm_source.category
     * @return  the value of tb_utm_source.category
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_utm_source.category
     * @param category  the value for tb_utm_source.category
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_utm_source.platform
     * @return  the value of tb_utm_source.platform
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_utm_source.platform
     * @param platform  the value for tb_utm_source.platform
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_utm_source.charge_type
     * @return  the value of tb_utm_source.charge_type
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_utm_source.charge_type
     * @param chargeType  the value for tb_utm_source.charge_type
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public void setChargeType(String chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_utm_source.abbreviation
     * @return  the value of tb_utm_source.abbreviation
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_utm_source.abbreviation
     * @param abbreviation  the value for tb_utm_source.abbreviation
     * @mbggenerated  Tue Aug 25 14:56:50 CST 2015
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }
}